### ISSUE TITLE
0.9.0-alpha.3

### ISSUE THREAD

**Issue by wewoor** [DTStack/molecule#144]
# 0.9.0-alpha.3

## Workbench

- [x] Appearance needs re-layout after the show or hide #97  @mumiao 
- [x] Search Pane 功能完善 #111  @wewoor 
- [x] Problems enhancement #110 @PKaPI 

## Theme

- [x] Optimize the Color Theme #27 @wewoor 

## Internationalization

- [x] 基本的国际化能力，默认英文/中文 #106 #107  @wewoor 

## KeyBinding

- [x] 支持通过修改 settings 配置文件，来自定义部分内置功能的热键 #71  @PKaPI 

## Global

- [x] Design the Molecule open API and docs @wewoor 
- [x] API Review #105  @wewoor 
- [x] Provide QuickAccessInput Service #83 @wewoor 

## Other

- [x] Editor Tabs overflow scroll invalid #93
