### ISSUE TITLE
0.9.0-alpha.4

### ISSUE THREAD

**Issue by wewoor** [DTStack/molecule#271]
# 0.9.0-alpha.4

## Workbench

- [x] 优化 Icon prefix 名称 #262  @ProfBramble 
- [x] 优化 Editor Tab Icon 位置 #263 @mortalYoung 
- [x] MenuBar 默认菜单功能完善/优化 @ProfBramble 
- [x] Scrollable 优化 #230 @mortalYoung 

## Theme

- [x] Optimize the Color Theme #259 @mortalYoung 

## Internationalization

- [x] 优化国际化功能 #191 @ProfBramble 

## KeyBinding
无
## Global

- [x] 添加接口文档注释 #261  @wewoor @mortalYoung @ProfBramble 
- [x] 代码走查 / API Review #182 #105  @wewoor @mortalYoung @ProfBramble 
- [x] API 自动补全提示优化 #231 @ProfBramble 

## Other

- DAGScheduleX 适配测试开发 @wewoor @mortalYoung @ProfBramble 
- Bugfix  @wewoor @mortalYoung @ProfBramble 
- Self Testing #69  @wewoor @mortalYoung @ProfBramble
