### ISSUE TITLE
The Molecule Roadmap 2021

### ISSUE THREAD

**Issue by wewoor** [DTStack/molecule#3]
# The Molecule Roadmap 2021

### Workbench

- [x] 完善 Workbench 基本的 Editor, Sidebar, ActivityBar, StatusBar, Menu，Explorer，Search 等基本功能

### 国际化

- [x] 基本的国际化能力，默认英文/中文

### Settings

- [x] 支持通过 JSON/UI 的方式完成基本的默认 Theme, Text Editor、Layout 设置

### KeyBinding

- [x] 支持通过修改 settings 配置文件，来自定义部分内置功能的热键

### Release Experimental Version
- [x] 官网和基本使用指南
- [x] 基本的 API 文档

## Q3
- [x] DAGScheduleX 落地
- [x] 单测补充
- [x] API 文档 & 使用指南（Tutorials)
- [x] 开发官方网站

## Q4

- [x] 文档完善/优化
- [x] 开放代码

### Document
- [x] 优化
