### ISSUE TITLE
0.9.0-alpha.5

### ISSUE THREAD

**Issue by wewoor** [DTStack/molecule#311]
# 0.9.0-alpha.5

## Workbench

无

## Theme
无

## Internationalization

- [x] 优化国际化功能 @wewoor  #191 #343 

## Settings

- [x] 完善设置功能，目前很多 Bug @wewoor #364 

## KeyBinding
无

### 基础组件（component)

- [x] actionBar @wewoor #321 
- [x] breadcrumb @mortalYoung #330 
- [x] button @ProfBramble #314 
- [x] checkbox @ProfBramble #320 
- [x] contextMenu @wewoor #322 
- [x] contextView @wewoor #324 
- [x] diaglog @ProfBramble #359  #327 
- [x] dropdown @wewoor #328 
- [x] icon @wewoor #329 
- [x] input @ProfBramble #335 
- [x] list @wewoor #333 
- [x] menu @ProfBramble #370 
- [x] monaco @ProfBramble #323 
- [x] WIP: scrollable @wewoor #380 
- [x] search @ProfBramble #345 
- [x] select @wewoor #340 
- [x] tabs @mortalYoung #339 
- [x] toolbar @mortalYoung #337 
- [x] tooltip @mortalYoung #332 
- [x] #334

### 工作台组件（Workbench View）

- [x] Workbench @wewoor #387 
- [x] ActivityBar @mortalYoung #382 
- [x] ActivityBarItem @mortalYoung #382 
- [x] Editor @ProfBramble 
- [x] EditorGroup @ProfBramble 
- [x] MenuBar @ProfBramble #385 
- [x] Panel @wewoor #392 
- [x] Sidebar @mortalYoung 
    - #393 
    - #386
    - #391 
- [x] StatusBar @mortalYoung #383 
- [x] StatusItem @mortalYoung #383 
- [x]  Problems @mortalYoung #394 
- [x] Notification @wewoor #399 

### 服务（Services）

- [x] ExtensionService @wewoor  #342 
- [x] ColorThemeService @mortalYoung  #344 
- [x] NotificationService @mortalYoung  #346 
- [x] ProblemsService @mortalYoung  #348 
- [x] SettingsService @wewoor #364  #355 
- [x] ActivityBarService @mortalYoung  #350 
- [x] EditorService @wewoor #376 
- [x] LayoutService @mortalYoung #356 
- [x] MenuBarService @mortalYoung  #365 
- [x] PanelService @mortalYoung #372 
- [x] SearchService @ProfBramble #374 
- [x] SidebarService @mortalYoung #373 
- [x] StatusBarService @mortalYoung #375 
- [x] EditorTreeService @ProfBramble #377 
- [x] ExplorerService @mortalYoung #378 
- [x] FolderTreeService @ProfBramble #384 
- [x] LocaleService @wewoor #191 #399 

## Global

- [x] 添加接口文档注释 #261  @wewoor @mortalYoung @ProfBramble 
- [x] 重构 React 引入模式 @ProfBramble  #312 

## Other 
- DAGScheduleX 适配测试开发 @wewoor @mortalYoung @ProfBramble 

## Long Term Tasks

- Bugfix  @wewoor @mortalYoung @ProfBramble 
- Self Testing #69  @wewoor @mortalYoung @ProfBramble 
- **Optimize the Color Theme**
