### ISSUE TITLE
 0.9.0-alpha.1

### ISSUE THREAD

**Issue by wewoor** [DTStack/molecule#4]
#### Sidebar
- [ ] Explorer Actions 支持隐藏/显示 OPEN EDITORS  #9 
- [ ] Explorer TreeView 支持增、删、改操作 #10 
- [ ] Search Pane 支持简单文本/正则搜索规则，和搜索结果展示树 #11 
- [ ] 重构 Explorer 模块代码 #12 

#### Editor
- [ ] Editor 支持 Close Others, Close To Left, Close To Right, Close All 等基本功能 #13 
- [ ] Menu 菜单 Edit 支持 Undo, Redo 触发 #14 
- [ ] 支持自定义 Editor  Renderer, 根据 Tab Data 具体展示面板 #15 

#### Menu
- [ ] 支持 Settings 菜单触发 Command Palette #16 

#### ActivityBar

- [ ] 支持基本的上下文菜单 #28 
- [ ] 支持显示隐藏 MenuBar/Search/Explorer 等操作 #28 

#### StatusBar

- [ ] 支持统计显示来自 EditorText 的 Errors 和 Warnings 信息（Problems) #17 
- [ ] 支持消息面板的查阅，推送，清除功能 #18 

#### Panel

- [ ] 支持 Panel 的展示/关闭 #19 
- [ ] 支持 Panel 增加/删除/修改默认面板（Pane） #21 
- [ ] 支持展示 Problems 具体信息 #20 
- [ ] 支持默认的 Output 面板，基本的 Append, Clear 等操作 #22 

#### Appearance

- [ ] 显示隐藏 MenuBar #23 
- [ ] 显示隐藏 SideBar，支持通过点击 Explorer/Search  打开 Siebar #24 
- [ ] 显示隐藏 StatusBar #25 
- [ ] 显示隐藏 ActivityBar #26 

## ColorTheme

- [ ] 优化 Monaco 部分样式无法显示的问题，部分组件颜色取错的问题 #27
