### ISSUE TITLE
v0.9.0-beta.2

### ISSUE THREAD

**Issue by wewoor** [DTStack/molecule#542]
# v0.9.0-beta.2

## Docs
- [x] 收集展示示例（examples) 
- [x] 社区宣广文章一篇 #539 @wewoor 
- [x] Translate the Docs in English #546  @kiwiwong  @mortalYoung 
- [x] Add **Korean** README #568 @SQLGate 

## Features
- [x] MenuBar 支持顶部 horizontal 模式 #457 @kiwiwong 
- [ ] #545 @wewoor 
- [x] Add **Korean** locales source #558   @SQLGate 

## Refactoring

- [x] Update the Declaration of Interfaces #455 @wewoor 
- [x] Expose the Action2 type #532 @wewoor 

## Bug

- [x] StatusBar hidden 布局计算异常 ref #457 @kiwiwong 
- [x] #580 @wewoor
