### ISSUE TITLE
Molecule 2.0 TODO List

### ISSUE THREAD

**Issue by mortalYoung** [DTStack/molecule#858]
自 2022 年 6 月 17 日发布 v1.0.0 以来，Molecule 共发布了 10 个版本。期间修复了大量 Bug，稳定现有功能。但也有一些问题日积月累，已经无法通过修复来确保代码的可维护性和健壮性。因此，我们计划启动 2.0 的开发，旨在彻底解决性能优化问题、布局优化问题等问题，同时优化 Molecule 相关的开发体验。

Since the release of v1.0.0 in 2022.06.17, Molecule has released a total of 10 versions. During this period, a large number of bugs were fixed and existing functions were stabilized. But there are some problems that have accumulated and cannot be repaired to achieve both maintainability and robustness of the code. Therefore, we plan to start the development of 2.0, aiming to completely solve the performance optimization problem, layout optimization problem and other issues, and optimize the Molecule-related development experience.

# 更新内容
- 性能优化，提升相关性能，为大数据保驾护航
- 布局优化，简化重构布局的步骤，轻松重写当前布局
- 主题优化，主题继承更智能

# Roadmap
- [ ] kick-off
- [ ] RoadMap
- [ ] 分支清理，项目基础搭建
	- [ ] dev playgroud 搭建
- [ ] CI
- [ ] Glue
    - [ ] tsyringe 改造，支持多例
    - [ ] Connector 优化，支持依赖自收集
    - [ ] baseService and baseController 优化，定义 service 和 controller 的抽象
    - [ ] eventEmitter 支持 bail hook
    - [ ] abstract Component 的 setState 优化
- [ ] Service 迁移，支持多例，支持 pure method 和 effect method
	- [ ] Instance，多例入口
	- [ ] Extension
	- [ ] keybinding
	- [ ] notification
	- [ ] problems
	- [ ] settings
	- [ ] BuiltinService，处理 builtin 的数据
	- [ ] colorTheme，主题系统优化
	- [ ] layout
	- [ ] activityBar
	- [ ] auxiliaryBar
	- [ ] editor
	- [ ] layout
	- [ ] menuBar
	- [ ] panel
	- [ ] search
	- [ ] sideBar
	- [ ] statusBar
- [ ] controller 迁移
	- [ ] activityBar
	- [ ] auxiliaryBar
	- [ ] editor
	- [ ] extension
	- [ ] layout
	- [ ] menuBar
	- [ ] notification
	- [ ] panel
	- [ ] problems
	- [ ] settings
	- [ ] sideBar
	- [ ] statusBar
	- [ ] search
	- [ ] editorTree
	- [ ] explorer
	- [ ] folderTree
	- [ ] outline
- [ ] Client 改造
	- [ ] 支持 swizzle
	- [ ] 简化 React 组件，易于重写
	- [ ] 加载方式优化，通过 Controller 加载组件
- [ ] 单测补充
- [ ] website 更新
- [ ] migrate 文档更新

**Comment by mumiao** [comment]
👍🏻

**Comment by WheatMaThink** [comment]
国内少有的精品软件！

宣传上可以加强，让更多的开发者加入。

**Comment by octoape** [comment]
是否考虑实现一个表格组件，用于诸如数据展示和编辑的场景。

**Comment by yibn2008** [comment]
2.0 稳定版大概会在什么时候发布？

**Comment by mortalYoung** [comment]
> 2.0 稳定版大概会在什么时候发布？

原定计划是年内发布 beta 版本，后续补充文档和测试用例就发布正式版。目前看来可能会比原计划延期一个月左右的时间。
